services:
  podmixer:
    image: docker.io/atareao/podmixer:v0.2.0
    container_name: podmixer
    restart: unless-stopped
    init: true
    volumes:
      - db:/app/db
      - rss:/app/rss
    ports:
      - 3000:3000
    environment:
      RUST_LOG: debug
      RUST_BACKTRACE: "full"
      RUST_ENV: production
      DB_URL: /app/db/podmixer.db
      PORT: 3000
      SECRET: esto-es-un-secreto-que-no-se-puede-saber
      SLEEP_TIME: 900
      OLDER_THAN: 10
  ubuntu:
    image: ubuntu
    container_name: ubuntu
    init: true
    volumes:
      - db:/db

volumes:
  db: {}
  rss: {}
